go
use WHiring;

CREATE NONCLUSTERED INDEX indx_VACANCY_Salary ON VACANCY(MinSalary, MaxSalary);
CREATE NONCLUSTERED INDEX indx_VACANCY_SalaryD ON VACANCY(MinSalary DESC, MaxSalary DESC);
CREATE NONCLUSTERED INDEX indx_VACANCY_Level ON VACANCY(Level);
CREATE NONCLUSTERED INDEX indx_VACANCY_LevelD ON VACANCY(Level DESC);

CREATE NONCLUSTERED INDEX indx_WORKER_Salary ON WORKER(Salary);
CREATE NONCLUSTERED INDEX indx_WORKER_SalaryD ON WORKER(Salary DESC);
CREATE NONCLUSTERED INDEX indx_WORKER_Level ON WORKER(Level);
CREATE NONCLUSTERED INDEX indx_WORKER_LevelD ON WORKER(Level DESC);

CREATE NONCLUSTERED INDEX indx_CANDIDATE_Salary ON CANDIDATE(Salary);
CREATE NONCLUSTERED INDEX indx_CANDIDATE_SalaryD ON CANDIDATE(Salary);
CREATE NONCLUSTERED INDEX indx_CANDIDATE_Level ON CANDIDATE(Level);
CREATE NONCLUSTERED INDEX indx_CANDIDATE_LevelD ON CANDIDATE(Level DESC);